# Generated by Django 5.2.3 on 2025-06-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('published_date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('page_count', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=30)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
            ],
        ),
    ]
